// Rich per-city dataset for the interactive (selective) rankings page.
// Each city carries hazard flags (bitmask) and raw society indicators, so the
// page can filter and reweight live.
// Run with: node --experimental-strip-types scripts/generate-citydata.ts
import { writeFileSync } from 'node:fs';
import allCitiesPkg from 'all-the-cities';
import countriesPkg from 'world-countries';
import { zones } from '../../src/lib/data/zones/zones.ts';
import { zoneRadiusDeg } from '../../src/lib/data/scales/reach.ts';
import { lifeExpectancy } from '../../src/lib/data/generated/life-expectancy.ts';
import { indicators } from '../../src/lib/data/generated/indicators.ts';

const allCities = (allCitiesPkg.default ?? allCitiesPkg).slice().sort((a, b) => b.population - a.population);
const countries = countriesPkg.default ?? countriesPkg;

const iso2to3 = new Map();
const iso3name = new Map();
for (const c of countries) {
	if (c.cca2 && c.cca3) {
		iso2to3.set(c.cca2.toUpperCase(), c.cca3);
		iso3name.set(c.cca3, c.name.common);
	}
}

function angDeg(la1, lo1, la2, lo2) {
	const r = Math.PI / 180;
	const a1 = la1 * r;
	const a2 = la2 * r;
	const dl = (lo2 - lo1) * r;
	const c = Math.sin(a1) * Math.sin(a2) + Math.cos(a1) * Math.cos(a2) * Math.cos(dl);
	return (Math.acos(Math.max(-1, Math.min(1, c))) * 180) / Math.PI;
}

const zoneInfo = zones.map((z) => ({
	lat: z.lat,
	lng: z.lng,
	rd: zoneRadiusDeg(z),
	tier: z.tier,
	radon: /radon/i.test(z.name)
}));

// Bitmask: EST=1 UV=2 RADON=4 GRAY=8 MAN=16 CONFLICT=32 CLIMATE=64
function flags(lat, lng) {
	let f = 0;
	for (const z of zoneInfo) {
		if (angDeg(lat, lng, z.lat, z.lng) > z.rd) continue;
		if (z.tier === 'established') f |= 1;
		else if (z.tier === 'anthropogenic') f |= 16;
		else if (z.tier === 'conflict') f |= 32;
		else if (z.tier === 'gray') f |= z.radon ? 4 : 8;
		else if (z.tier === 'climate') f |= 64;
	}
	if (Math.abs(lat) <= 35) f |= 2;
	return f;
}

const seen = new Set();
const cands = [];
for (const c of allCities) {
	if (c.population < 300000) continue;
	const iso3 = iso2to3.get((c.country || '').toUpperCase());
	if (!iso3 || lifeExpectancy[iso3] == null) continue;
	const key = `${c.name.toLowerCase()}|${iso3}`;
	if (seen.has(key)) continue;
	seen.add(key);
	const lat = +c.loc.coordinates[1].toFixed(2);
	const lng = +c.loc.coordinates[0].toFixed(2);
	cands.push({
		name: c.name,
		country: iso3name.get(iso3) || iso3,
		lat,
		lng,
		pop: c.population,
		le: lifeExpectancy[iso3] ?? null,
		hdi: indicators.hdi?.[iso3] ?? null,
		inc: indicators.income?.[iso3] ?? null,
		gini: indicators.gini?.[iso3] ?? null,
		hom: indicators.homicide?.[iso3] ?? null,
		f: flags(lat, lng)
	});
}

// Dedup near-duplicates within ~0.5 degrees, keeping the largest.
const dedup = [];
for (const c of cands) {
	if (dedup.some((d) => angDeg(c.lat, c.lng, d.lat, d.lng) < 0.5)) continue;
	dedup.push(c);
}
const out = dedup.map(({ pop, ...rest }) => rest); // drop pop from output

// Climate comfort from Open-Meteo archive (free, no key, multi-coordinate):
// mean 2024 temperature, fraction of mild days (10-24C), and sunshine hours.
async function fetchClimate(cities) {
	const CH = 50;
	for (let i = 0; i < cities.length; i += CH) {
		const slice = cities.slice(i, i + CH);
		const lat = slice.map((c) => c.lat).join(',');
		const lng = slice.map((c) => c.lng).join(',');
		const url = `https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lng}&start_date=2024-01-01&end_date=2024-12-31&daily=temperature_2m_mean,sunshine_duration&timezone=GMT`;
		try {
			const res = await fetch(url);
			if (!res.ok) throw new Error(`climate ${res.status}`);
			let data = await res.json();
			if (!Array.isArray(data)) data = [data];
			for (let j = 0; j < data.length; j++) {
				const c = slice[j];
				const d = data[j]?.daily;
				if (!d) {
					c.clim = null;
					c.temp = null;
					continue;
				}
				const t = (d.temperature_2m_mean || []).filter((x) => x != null);
				const meanT = t.length ? t.reduce((a, b) => a + b, 0) / t.length : null;
				const mild = t.length ? t.filter((x) => x >= 10 && x <= 24).length / t.length : 0;
				const sunH = (d.sunshine_duration || []).reduce((a, b) => a + (b || 0), 0) / 3600;
				const sNorm = Math.max(0, Math.min(1, (sunH - 1200) / (3000 - 1200)));
				c.clim = meanT == null ? null : Math.round(100 * (0.6 * mild + 0.4 * sNorm));
				c.temp = meanT == null ? null : Math.round(meanT * 10) / 10;
			}
		} catch (err) {
			console.warn('\nclimate chunk failed:', err.message);
			for (const c of slice) {
				c.clim = c.clim ?? null;
				c.temp = c.temp ?? null;
			}
		}
		process.stdout.write('.');
	}
	process.stdout.write('\n');
}
await fetchClimate(out);

const file =
	`// AUTO-GENERATED by scripts/generate/citydata.ts. Do not edit by hand.\n` +
	`// Hazard flags bitmask: EST=1 UV=2 RADON=4 GRAY=8 MAN=16 CONFLICT=32 CLIMATE=64.\n` +
	`export interface CityDatum { name: string; country: string; lat: number; lng: number; le: number|null; hdi: number|null; inc: number|null; gini: number|null; hom: number|null; f: number; clim: number|null; temp: number|null }\n` +
	`export const cityData: CityDatum[] = ${JSON.stringify(out)};\n`;

writeFileSync('src/lib/data/generated/citydata.ts', file);
console.log(`Wrote ${out.length} cities (from ${cands.length} candidates).`);
