// Assign sub-national (regional) life expectancy to cities where open data
// exists. Currently covers Europe via Eurostat NUTS-2 regions:
//   values: demo_r_mlifexp (life expectancy at birth, both sexes, latest year)
//   geometry: GISCO NUTS-2 boundaries (point-in-polygon by city coordinate)
// Output is keyed by "lat,lng" (3 decimals) to avoid name collisions.
// Usage: node scripts/generate-city-life-expectancy.ts
import { geoContains } from "d3-geo";
import { readFileSync, writeFileSync } from "node:fs";

const GISCO =
  "https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_20M_2021_4326_LEVL_2.geojson";
const EUROSTAT =
  "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/demo_r_mlifexp?format=JSON&lang=EN&sex=T&age=Y_LT1&lastTimePeriod=1";

// Read the city list straight from the generated places file.
const placesSrc = readFileSync("src/lib/data/generated/places.ts", "utf8");
const m = placesSrc.match(
  /export const cities: CityLabel\[\] = (\[[\s\S]*?\]);/,
);
if (!m) throw new Error("Could not parse cities from places.ts");
const cities = JSON.parse(m[1]);

// Eurostat regional life expectancy, keyed by NUTS code.
const stat = await (await fetch(EUROSTAT)).json();
const geoIndex = stat.dimension.geo.category.index;
const values = stat.value;
const year = stat.dimension.time.category.index
  ? Object.keys(stat.dimension.time.category.index)[0]
  : "";
const leByCode = {};
for (const [code, pos] of Object.entries(geoIndex)) {
  const v = values[pos];
  if (typeof v === "number") leByCode[code] = v;
}

// NUTS-2 region polygons that have a life expectancy value.
const gj = await (await fetch(GISCO)).json();
const regions = [];
for (const f of gj.features) {
  const code = f.properties.NUTS_ID ?? f.properties.id;
  const le = leByCode[code];
  if (typeof le === "number") regions.push({ feature: f, le });
}

const map = {};
let matched = 0;
for (const c of cities) {
  const pt = [c.lng, c.lat];
  for (const r of regions) {
    if (geoContains(r.feature, pt)) {
      map[`${c.lat.toFixed(3)},${c.lng.toFixed(3)}`] =
        Math.round(r.le * 10) / 10;
      matched++;
      break;
    }
  }
}

const out =
  `// AUTO-GENERATED by scripts/generate/city-life-expectancy.ts. Do not edit by hand.\n` +
  `// Sub-national (regional) life expectancy at birth for cities, where open data exists.\n` +
  `// Europe: Eurostat NUTS-2 demo_r_mlifexp (${year}), assigned by point-in-polygon.\n` +
  `// Keyed by "lat,lng" (3 decimals) matching the city list in places.ts.\n` +
  `export const cityLifeExpectancySource = 'Eurostat NUTS-2 regional, ${year}';\n` +
  `export const cityLifeExpectancy: Record<string, number> = ${JSON.stringify(map)};\n`;

writeFileSync("src/lib/data/generated/city-life-expectancy.ts", out);
console.log(
  `Matched ${matched} cities to ${regions.length} NUTS-2 regions (year ${year}).`,
);
