// Bake country socioeconomic indicators for optional map layers.
// World Bank (open, no key): Gini, GNI per capita (PPP), intentional homicide,
// universal health-coverage index. Plus an attempt at UNDP HDI.
// Usage: node scripts/generate-indicators.ts
import { writeFileSync } from 'node:fs';

const WB = {
	gini: { code: 'SI.POV.GINI', label: 'Gini (inequality)', unit: '', higherBetter: false },
	income: {
		code: 'NY.GNP.PCAP.PP.CD',
		label: 'Income (GNI per capita, PPP)',
		unit: 'intl $',
		higherBetter: true
	},
	homicide: {
		code: 'VC.IHR.PSRC.P5',
		label: 'Homicide rate',
		unit: 'per 100k',
		higherBetter: false
	},
	uhc: {
		code: 'SH.UHC.SRVS.CV.XD',
		label: 'Health coverage (UHC index)',
		unit: '',
		higherBetter: true
	}
};

async function fetchWB(code) {
	const url = `https://api.worldbank.org/v2/country/all/indicator/${code}?format=json&mrnev=1&per_page=400`;
	const json = await (await fetch(url)).json();
	const rows = json[1] ?? [];
	const map = {};
	let year = '';
	for (const r of rows) {
		if (r.countryiso3code && typeof r.value === 'number') {
			map[r.countryiso3code] = Math.round(r.value * 10) / 10;
			if (r.date > year) year = r.date;
		}
	}
	return { map, year };
}

function domain(map) {
	const v = Object.values(map).sort((a, b) => a - b);
	if (!v.length) return [0, 1];
	const p = (q) => v[Math.min(v.length - 1, Math.max(0, Math.floor(q * (v.length - 1))))];
	return [p(0.02), p(0.98)];
}

const indicators = {};
const indicatorMeta = {};

for (const [key, def] of Object.entries(WB)) {
	const { map, year } = await fetchWB(def.code);
	indicators[key] = map;
	indicatorMeta[key] = {
		label: def.label,
		source: 'World Bank',
		year,
		unit: def.unit,
		higherBetter: def.higherBetter,
		domain: domain(map)
	};
	console.log(`${key}: ${Object.keys(map).length} countries (year ${year})`);
}

// Attempt UNDP HDI (composite indices CSV). Skips gracefully if unavailable.
const HDI_URLS = [
	'https://hdr.undp.org/sites/default/files/2023-24_HDR/HDR23-24_Composite_indices_complete_time_series.csv',
	'https://hdr.undp.org/sites/default/files/2021-22_HDR/HDR21-22_Composite_indices_complete_time_series.csv'
];
let hdi = {};
let hdiYear = '';
for (const url of HDI_URLS) {
	try {
		const res = await fetch(url);
		if (!res.ok) continue;
		const text = await res.text();
		const lines = text.split(/\r?\n/);
		const header = lines[0].split(',');
		const isoIdx = header.indexOf('iso3');
		let hdiIdx = -1;
		for (let i = 0; i < header.length; i++) if (/^hdi_\d{4}$/.test(header[i])) hdiIdx = i;
		if (isoIdx < 0 || hdiIdx < 0) continue;
		hdiYear = header[hdiIdx].slice(4);
		for (let i = 1; i < lines.length; i++) {
			const cols = lines[i].split(',');
			const iso = cols[isoIdx];
			const val = parseFloat(cols[hdiIdx]);
			if (iso && iso.length === 3 && val >= 0.2 && val <= 1) hdi[iso] = Math.round(val * 1000) / 1000;
		}
		if (Object.keys(hdi).length > 100) break;
		hdi = {};
	} catch {
		// try next url
	}
}
if (Object.keys(hdi).length) {
	indicators.hdi = hdi;
	indicatorMeta.hdi = {
		label: 'HDI',
		source: 'UNDP',
		year: hdiYear,
		unit: '',
		higherBetter: true,
		domain: domain(hdi)
	};
	console.log(`hdi: ${Object.keys(hdi).length} countries (year ${hdiYear})`);
} else {
	console.log('hdi: unavailable from UNDP (skipped)');
}

const out =
	`// AUTO-GENERATED by scripts/generate/indicators.ts. Do not edit by hand.\n` +
	`export interface IndicatorMeta { label: string; source: string; year: string; unit: string; higherBetter: boolean; domain: [number, number] }\n` +
	`export const indicators: Record<string, Record<string, number>> = ${JSON.stringify(indicators)};\n` +
	`export const indicatorMeta: Record<string, IndicatorMeta> = ${JSON.stringify(indicatorMeta)};\n`;

writeFileSync('src/lib/data/generated/indicators.ts', out);
console.log('Wrote src/lib/data/generated/indicators.ts');
