// Bake life expectancy at birth (years) per country from the World Bank API.
// Indicator SP.DYN.LE00.IN, most recent non-empty value, keyed by ISO3 code.
// Usage: node scripts/generate-life-expectancy.ts
import { writeFileSync } from 'node:fs';

const URL =
	'https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?format=json&mrnev=1&per_page=400';

const res = await fetch(URL);
if (!res.ok) throw new Error(`World Bank API ${res.status}`);
const json = await res.json();
const rows = json[1] ?? [];

const map = {};
let latest = '';
for (const r of rows) {
	if (r.countryiso3code && typeof r.value === 'number') {
		map[r.countryiso3code] = Math.round(r.value * 10) / 10;
		if (r.date > latest) latest = r.date;
	}
}

const out =
	`// AUTO-GENERATED by scripts/generate/life-expectancy.ts. Do not edit by hand.\n` +
	`// Source: World Bank SP.DYN.LE00.IN, most recent value per country (through ${latest}).\n` +
	`// Years are national life expectancy at birth, keyed by ISO 3166-1 alpha-3 code.\n` +
	`export const lifeExpectancyYear = '${latest}';\n` +
	`export const lifeExpectancy: Record<string, number> = ${JSON.stringify(map)};\n`;

writeFileSync('src/lib/data/generated/life-expectancy.ts', out);
console.log(`Wrote life expectancy for ${Object.keys(map).length} entries (latest ${latest}).`);
