// Generate src/lib/data/generated/places.ts from real datasets.
// Cities with population >= 1.5M (from all-the-cities) plus a curated list of
// globally significant smaller cities, and country labels (from world-countries).
// Usage: node scripts/generate-places.ts
import { writeFileSync } from 'node:fs';
import allCitiesPkg from 'all-the-cities';
import countriesPkg from 'world-countries';

const allCities = allCitiesPkg.default ?? allCitiesPkg;
const countries = countriesPkg.default ?? countriesPkg;

const MIN_POP = 1_500_000;
const MAX_CITIES = 400;

// Significant smaller cities (cultural, scientific, historic, or atlas-relevant).
const SIGNIFICANT = [
	{ name: 'Geneva', lat: 46.2, lng: 6.14 },
	{ name: 'Davos', lat: 46.8, lng: 9.83 },
	{ name: 'Mecca', lat: 21.42, lng: 39.83 },
	{ name: 'Medina', lat: 24.47, lng: 39.61 },
	{ name: 'Jerusalem', lat: 31.78, lng: 35.22 },
	{ name: 'Vatican City', lat: 41.9, lng: 12.45 },
	{ name: 'Reykjavik', lat: 64.15, lng: -21.94 },
	{ name: 'Venice', lat: 45.44, lng: 12.32 },
	{ name: 'Kyoto', lat: 35.01, lng: 135.77 },
	{ name: 'Hiroshima', lat: 34.39, lng: 132.46 },
	{ name: 'Lhasa', lat: 29.65, lng: 91.1 },
	{ name: 'Kathmandu', lat: 27.7, lng: 85.32 },
	{ name: 'Cusco', lat: -13.53, lng: -71.97 },
	{ name: 'Timbuktu', lat: 16.77, lng: -3.0 },
	{ name: 'Salzburg', lat: 47.81, lng: 13.05 },
	{ name: 'Monaco', lat: 43.74, lng: 7.42 },
	{ name: 'Cambridge', lat: 52.21, lng: 0.12 },
	{ name: 'Oxford', lat: 51.75, lng: -1.26 },
	{ name: 'Ramsar', lat: 36.9, lng: 50.66 },
	{ name: 'Rotorua', lat: -38.14, lng: 176.25 }
];

const cities = allCities
	.filter((c) => c.population >= MIN_POP)
	.map((c) => ({
		name: c.name,
		lat: c.loc.coordinates[1],
		lng: c.loc.coordinates[0],
		pop: c.population
	}))
	.sort((a, b) => b.pop - a.pop)
	.slice(0, MAX_CITIES);

const known = new Set(cities.map((c) => c.name.toLowerCase()));
const significant = SIGNIFICANT.filter((s) => !known.has(s.name.toLowerCase())).map((s) => ({
	...s,
	pop: 0,
	significant: true
}));
for (const s of significant) known.add(s.name.toLowerCase());

// world-countries has capital names but not coordinates, so resolve each
// capital against all-the-cities, scoped by country (ISO2) with a name fallback.
const byCountryName = new Map();
const byName = new Map();
for (const c of allCities) {
	const loc = { lat: c.loc.coordinates[1], lng: c.loc.coordinates[0], pop: c.population };
	const ck = `${(c.country || '').toLowerCase()}|${c.name.toLowerCase()}`;
	const prev = byCountryName.get(ck);
	if (!prev || loc.pop > prev.pop) byCountryName.set(ck, loc);
	const nk = c.name.toLowerCase();
	const prevN = byName.get(nk);
	if (!prevN || loc.pop > prevN.pop) byName.set(nk, loc);
}

const capitals = [];
let unresolved = 0;
for (const c of countries) {
	const name = Array.isArray(c.capital) ? c.capital[0] : null;
	if (!name) continue;
	const key = name.toLowerCase();
	if (known.has(key)) continue;
	const iso2 = (c.cca2 || '').toLowerCase();
	const loc = byCountryName.get(`${iso2}|${key}`) ?? byName.get(key);
	if (!loc) {
		unresolved++;
		continue;
	}
	known.add(key);
	capitals.push({ name, lat: loc.lat, lng: loc.lng, pop: 0, capital: true });
}

// Geographic coverage fill: ensure even sparse regions (Alaska, Siberia, the
// Sahel, outback, etc.) show a city. Bin the globe into cells and add the top
// city in any cell not already represented by a major city or capital.
const COVERAGE_FLOOR = 75_000;
const CELL = 6; // degrees
const cellTop = new Map();
for (const c of allCities) {
	if (c.population < COVERAGE_FLOOR) continue;
	const lat = c.loc.coordinates[1];
	const lng = c.loc.coordinates[0];
	const key = `${Math.floor((lat + 90) / CELL)}_${Math.floor((lng + 180) / CELL)}`;
	const arr = cellTop.get(key) ?? [];
	arr.push(c);
	cellTop.set(key, arr);
}
const coverage = [];
for (const arr of cellTop.values()) {
	arr.sort((a, b) => b.population - a.population);
	let represented = false;
	for (const c of arr) {
		if (known.has(c.name.toLowerCase())) {
			represented = true;
			break;
		}
	}
	if (represented) continue; // cell already has a major city or capital
	const top = arr[0];
	known.add(top.name.toLowerCase());
	coverage.push({
		name: top.name,
		lat: top.loc.coordinates[1],
		lng: top.loc.coordinates[0],
		pop: top.population
	});
}

const countryLabels = countries
	.filter((c) => Array.isArray(c.latlng) && c.latlng.length === 2)
	.map((c) => ({ name: c.name.common, lat: c.latlng[0], lng: c.latlng[1], iso3: c.cca3 }));

const out =
	`// AUTO-GENERATED by scripts/generate/places.ts. Do not edit by hand.\n` +
	`export interface CityLabel { name: string; lat: number; lng: number; pop: number; significant?: boolean; capital?: boolean }\n` +
	`export interface CountryLabel { name: string; lat: number; lng: number; iso3: string }\n\n` +
	`export const cities: CityLabel[] = ${JSON.stringify([...cities, ...significant, ...capitals, ...coverage])};\n\n` +
	`export const countryLabels: CountryLabel[] = ${JSON.stringify(countryLabels)};\n`;

writeFileSync('src/lib/data/generated/places.ts', out);
console.log(
	`Wrote ${cities.length} cities + ${significant.length} significant + ${capitals.length} capitals (${unresolved} unresolved) + ${coverage.length} coverage, ${countryLabels.length} countries.`
);
